eureka:
  client:
    serviceUrl:
      defaultZone: http://discoveryPaasOps.dev-ops.vip/eureka/
  instance:
    hostname: ${vcap.application.uris[0]}
    instance-id: api-gatewayPaasOps.dev-ops.vip  
    prefer-ip-address: false  
    nonSecurePort: 80 
    home-page-url: http://${eureka.instance.hostname}
    status-page-url: http://${eureka.instance.hostname}/info
    health-check-url: http://${eureka.instance.hostname}/health
server:
  port: 80

spring:
  application:
    name: api-gatewayPaasOps
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    password: qwer1234
    url: jdbc:mysql://124.251.110.251:3306/paasOpsDB?prepStmtCacheSize=517&cachePrepStmts=true&autoReconnect=true&characterEncoding=utf-8&allowMultiQueries=true
    username: paasOps
  jackson:
    serialization:
      indent_output: 'true'
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: vianet.paasOps.apiGateway.repository.EntityNamingStrategy
    show-sql: 'true'
  redis:
    host: 124.251.110.251
    password: '123456'
    port: '20001'
  session:
    redis:
      flush-mode: on_save
    store-type: redis
  cloud:
    loadbalancer:
      retry:
        enabled: true
zuul:
  add-host-header: true
  routes:
    api-a-url:
      path: /schedule/**
      url: http://schedule.devops.paas/
    feign-consumer:
      sensitiveHeaders: ''
    sensitive-headers: ''
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000
    
#ribbon:
#  ReadTimeout: 60000 
#  ConnectTimeout: 60000  
